apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hydra-ingress
  namespace: hydra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: hydra.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: central
                port:
                  number: 8080
